version: "3.3"

services:
  app:
    build: ./backend/service1/src
    container_name: my_python_app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
