services:
  app_base:
    build: ./backend/service1/src
    image: vibe-app-image:latest # Specify the custom image name and tag
    container_name: my_python_app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - ./models:/models
    environment:
      - PYTHONUNBUFFERED=1 # Disable output buffering
    stdin_open: true  # Keep the standard input open
    tty: true         # Allocate a pseudo-TTY

  app_linux:
    extends:
      service: app_base
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse # Mount PulseAudio socket for Linux

  app_macos:
    extends:
      service: app_base
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse # Mount PulseAudio socket for macOS

  app_windows:
    extends:
      service: app_base
    environment:
      - PULSE_SERVER=tcp:host.docker.internal # PulseAudio server for Windows
